---

- name: 'Create payara user group'
  group:
    name: '{{ payara_user }}'
    state: present

- name: 'Create payara user'
  user:
    name: '{{ payara_user }}'
    createhome: true
    group: '{{ payara_user }}'
    shell: /bin/bash

- name: 'Create downloads directory'
  file:
    path: /home/{{ payara_user }}/downloads
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create install directory'
  file:
    path: /home/{{ payara_user }}/install
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create scripts directory'
  file:
    path: /home/{{ payara_user }}/scripts
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Install payara init script'
  template:
    src: templates/payara-init.j2
    dest: '/usr/local/bin/payara-init'
    owner: root
    group: root
    mode: 0775

- name: 'Add path to payara executable to PATH variable'
  lineinfile:
    path: /home/{{ payara_user }}/.bashrc
    line: 'export PATH=$HOME/{{ payara_directory }}/bin:$PATH'

- name: 'Check payara package'
  stat:
    path: /home/{{ payara_user }}/downloads/payara-4.1.2.181.zip
  register: packageResult

- name: 'Download payara'
  get_url:
    url: http://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/4.1.2.181/payara-4.1.2.181.zip
    dest: /home/{{ payara_user }}/downloads
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check payara setup script'
  stat:
    path: /home/{{ payara_user }}/scripts/setup-glassfish.py
  register: scriptResult

- name: 'Download payara setup script'
  get_url:
    url: https://icatproject.org/misc/scripts/setup-glassfish.py
    dest: /home/{{ payara_user }}/scripts
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: scriptResult.stat.exists is defined and scriptResult.stat.exists == false

- name: 'Check payara installation'
  stat:
    path: /home/{{ payara_user }}/{{ payara_directory }}
  register: installationResult

- name: 'Unarchive payara if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/payara-4.1.2.181.zip
    dest: /home/{{ payara_user }}
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Setup payara if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.{{ heading }} is not defined) or (ansible_local.local.{{ heading }}.payara is not defined) or (ansible_local.local.{{ heading }}.payara != 'true')
