---

- hosts: icat-test-hosts
  become: true
  vars_files:
  - 'group_vars/all/vars.yml'
  vars:
    authn_simple_install: true
  roles:
  - role: common
  - role: java
  - role: mariadb
  - role: payara
  - role: authn-simple
  - role: icat-lucene
  - role: icat-server
  - role: ids-storage_file
  - role: ids-server
  - role: topcat
