---

- hosts: icat-dev-base-hosts
  become: true
  vars_files:
  - 'group_vars/all/vars.yml'
  roles:
  - role: common
  - role: java
  - role: mariadb
  - role: payara
  - role: authn-simple
  - role: icat-lucene
  - role: icat-server
  - role: ids-storage_file
  - role: ids-server
  - role: topcat
  - role: dev-common
  - role: authn-db
