---

- name: 'Check ids-storage_file package'
  stat:
    path: /home/glassfish/downloads/ids.storage_file-1.4.1-distro.zip
  register: packageResult

- name: 'Download ids-storage_file'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/ids.storage_file/1.4.1/ids.storage_file-1.4.1-distro.zip
    dest: /home/glassfish/downloads
    owner: glassfish
    group: glassfish
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check ids-storage_file installation'
  stat:
    path: /home/glassfish/install/ids.storage_file
  register: installationResult

- name: 'Unarchive ids-storage_file if not installed'
  unarchive:
    src: /home/glassfish/downloads/ids.storage_file-1.4.1-distro.zip
    dest: /home/glassfish/install
    remote_src: true
    owner: glassfish
    group: glassfish
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Configure ids-storage_file setup.properties'
  template:
    src: roles/payara/templates/setup.properties.j2
    dest: /home/glassfish/install/ids.storage_file/setup.properties
    owner: glassfish
    group: glassfish
    mode: 0600
  notify:
  - ids-storage_file-handler

- name: 'Setup ids-storage_file if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.ids_storage_file is not defined) or (ansible_local.local.instantiations.ids_storage_file != 'true')
