---

- name: 'Check ids-storage_file package'
  stat:
    path: /home/{{ payara_user }}/downloads/ids.storage_file-{{ ids_storage_file_version }}-distro.zip
  register: packageResult

- name: 'Download ids-storage_file'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/ids.storage_file/{{ ids_storage_file_version }}/ids.storage_file-{{ ids_storage_file_version }}-distro.zip
    dest: /home/{{ payara_user }}/downloads
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check ids-storage_file installation'
  stat:
    path: /home/{{ payara_user }}/install/ids.storage_file
  register: installationResult

- name: 'Unarchive ids-storage_file if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/ids.storage_file-{{ ids_storage_file_version }}-distro.zip
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Configure ids-storage_file setup.properties'
  template:
    src: roles/payara/templates/setup.properties.j2
    dest: /home/{{ payara_user }}/install/ids.storage_file/setup.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0600
  notify:
  - ids-storage_file-handler

- name: 'Setup ids-storage_file if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.ids_storage_file is not defined) or (ansible_local.local.instantiations.ids_storage_file != 'true')
