---

- name: 'Import: Check Payara is running'
  import_tasks: roles/payara/tasks/check-payara.yml

- name: 'Restart Payara if it is running'
  shell: '/usr/local/bin/payara-init restart'
  become: true
  become_user: root
  args:
    chdir: /root
    executable: /bin/bash
  when: payaraStatus.rc == 0
