---

- name: 'Install common ICAT dependencies'
  package: name={{ item }} state=present
  with_items:
  - python-suds
  - python-requests

- name: 'Install ICAT dependencies for Red Hat systems'
  package: name={{ item }} state=present
  with_items:
  - MySQL-python
  - mysql-connector-java
  when: ansible_os_family == 'RedHat'

- name: 'Install Java packages for Debian systems'
  package: name={{ item }} state=present
  with_items:
  - python-mysqldb
  - libmysql-java
  when: ansible_os_family == 'Debian'

- name: 'Create the GlassFish user'
  user:
    name: glassfish
    createhome: true
    shell: /bin/bash

- name: 'Create downloads directory structure for ICAT installation'
  file:
    path: /home/glassfish/downloads
    state: directory
    owner: glassfish
    group: glassfish
    mode: 0755

- name: 'Create install directory structure for ICAT installation'
  file:
    path: /home/glassfish/install
    state: directory
    owner: glassfish
    group: glassfish
    mode: 0755

- name: 'Create scripts directory structure for ICAT installation'
  file:
    path: /home/glassfish/scripts
    state: directory
    owner: glassfish
    group: glassfish
    mode: 0755
