---

- include_vars: vars/redhat.yml
  when: ansible_os_family == 'RedHat'

- include_vars: vars/debian.yml
  when: ansible_os_family == 'Debian'

- include_vars: roles/common/vars/main.yml

- name: 'Install mariadb packages'
  package: name={{ item }} state=present
  with_items: '{{ mariadb_pkgs }}'

- name: 'Configure default storage engine'
  copy:
    src: files/storage-engine.cnf
    dest: '{{ mariadb_config_dir }}/storage-engine.cnf'
    owner: root
    group: root
    mode: 0644
  notify:
  - mariadb-handler

- name: 'Configure default character set'
  copy:
    src: files/character-set.cnf
    dest: '{{ mariadb_config_dir }}/character-set.cnf'
    owner: root
    group: root
    mode: 0644
  notify:
  - mariadb-handler

- name: 'Remove any mariadb specific conf as these defaults override our own'
  lineinfile:
    path: '{{ mariadb_config_dir }}/../mycnf.cnf'
    regexp: '^\!includedir {{ mariadb_config_dir }}/mariadb.conf.d/'
    state: absent
  notify:
  - mariadb-handler

- name: 'Enable and start dbms daemon'
  service:
    name: '{{ mariadb_daemon }}'
    state: started
    enabled: true

- name: 'Setup mariadb if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.{{ heading }} is not defined) or (ansible_local.local.{{ heading }}.{{ mariadb_daemon }} is not defined) or (ansible_local.local.{{ heading }}.{{ mariadb_daemon }} != 'true')
