---

- include_vars: vars/redhat.yml
  when: ansible_os_family == 'RedHat'

- include_vars: vars/debian.yml
  when: ansible_os_family == 'Debian'

- name: 'Install mariadb packages'
  package: name={{ item }} state=present
  with_items: '{{ mariadb_pkgs }}'

- name: 'Configure default storage engine'
  copy:
    src: files/storage-engine.cnf
    dest: '{{ mariadb_config_dir }}/storage-engine.cnf'
    owner: root
    group: root
    mode: 0644
  notify:
  - mariadb-handler

- name: 'Enable and start dbms daemon'
  service:
    name: '{{ mariadb_daemon }}'
    state: started
    enabled: true

- name: 'Setup mariadb if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.{{ mariadb_daemon }} is not defined) or (ansible_local.local.instantiations.{{ mariadb_daemon }} != 'true')
