---

- name: 'Check ids-server package'
  stat:
    path: /home/{{ payara_user }}/downloads/ids.server-1.9.0-distro.zip
  register: packageResult

- name: 'Download ids-server'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/ids.server/1.9.0/ids.server-1.9.0-distro.zip
    dest: /home/{{ payara_user }}/downloads
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check ids-server installation'
  stat:
    path: /home/{{ payara_user }}/install/ids.server
  register: installationResult

- name: 'Unarchive ids-server if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/ids.server-1.9.0-distro.zip
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Create main data directory'
  file:
    path: /home/{{ payara_user }}/data/main
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create archive data directory'
  file:
    path: /home/{{ payara_user }}/data/archive
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create cache data directory'
  file:
    path: /home/{{ payara_user }}/data/cache
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create a stash directory for assembling configurations'
  file:
    path: /home/{{ payara_user }}/stash
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Create a stash directory for ids-server configs'
  file:
    path: /home/{{ payara_user }}/stash/ids-server
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Copy over {{ payara_user }} setup.properties'
  template:
    src: roles/payara/templates/setup.properties.j2
    dest: /home/{{ payara_user }}/stash/ids-server/1-part
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664

- name: 'Copy over ids-server setup.properties'
  copy:
    src: files/setup.properties
    dest: /home/{{ payara_user }}/stash/ids-server/2-part
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664

- name: 'Configure ids-server setup.properties by concatenation of files in the stash'
  assemble:
    src: /home/{{ payara_user }}/stash/ids-server
    dest: /home/{{ payara_user }}/install/ids.server/setup.properties
    delimiter: '\n'
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0600
  notify:
  - ids-server-handler

- name: 'Configure ids-server run.properties'
  template:
    src: templates/run.properties.j2
    dest: /home/{{ payara_user }}/install/ids.server/run.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - ids-server-handler

- name: 'Configure ids-server logback.xml'
  copy:
    src: files/logback.xml
    dest: /home/{{ payara_user }}/install/ids.server/logback.xml
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - ids-server-handler

- name: 'Setup ids-server if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.{{ heading }} is not defined) or (ansible_local.local.{{ heading }}.ids_server is not defined) or (ansible_local.local.{{ heading }}.ids_server != 'true')
