---

- name: 'Setup authn-db'
  import_tasks: handlers/authn-db-handler.yml

- name: 'Set fact on host to record that authn-db has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'authn_db'
    value: 'true'
    no_extra_spaces: true
    create: false
