---
- name: 'Edit topcatURL in topcat.json'
  shell: cat topcat.json.example | jq '.site.topcatUrl = "https://{{ topcat_url }}:8181"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Remove all facilities except LILS (the test facility)'
  shell: 'cat topcat.json | jq ''{site, facilities: [ .facilities[] | select(.name == "LILS") ], plugins}'' > tmp.json && mv tmp.json topcat.json'
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Edit idsUrl in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].idsUrl = "https://{{ ids_url }}:8181"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Edit icatUrl in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].icatUrl = "https://{{ icat_url }}:8181"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Set authenticationTypes to [] in LILS facility in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].authenticationTypes = []' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Add Simple authn in topcat.json'
  shell: 'cat topcat.json | jq ''.facilities[0].authenticationTypes += [{"title": "Simple", "plugin": "simple"}]'' > tmp.json && mv tmp.json topcat.json'
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash
  when: authn_simple is defined and authn_simple

- name: 'Add DB authn in topcat.json'
  shell: 'cat topcat.json | jq ''.facilities[0].authenticationTypes += [{"title": "DB", "plugin": "db"}]'' > tmp.json && mv tmp.json topcat.json'
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash
  when: authn_db is defined and authn_db

- name: 'Add Anon authn in topcat.json'
  shell: 'cat topcat.json | jq ''.facilities[0].authenticationTypes += [{"title": "Anonymous", "plugin": "anon"}]'' > tmp.json && mv tmp.json topcat.json'
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash
  when: authn_anon is defined and authn_anon

- name: 'Add LDAP authn in topcat.json'
  shell: 'cat topcat.json | jq ''.facilities[0].authenticationTypes += [{"title": "LDAP", "plugin": "ldap"}]'' > tmp.json && mv tmp.json topcat.json'
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash
  when: authn_ldap is defined and authn_ldap

- name: 'Set http transport type in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].downloadTransportTypes[0].type = "http"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Edit http download idsUrl in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].downloadTransportTypes[0].idsUrl = "http://{{ ids_url }}:8080"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Set https transport type in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].downloadTransportTypes[1].type = "https"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Edit https download idsUrl in topcat.json'
  shell: cat topcat.json | jq '.facilities[0].downloadTransportTypes[1].idsUrl = "https://{{ ids_url }}:8181"' > tmp.json && mv tmp.json topcat.json
  become: true
  become_user: '{{ payara_user }}'
  args:
    chdir: /home/{{ payara_user }}/install/topcat
    executable: /bin/bash

- name: 'Remove intermediate file'
  file:
    path: /home/{{ payara_user }}/install/topcat/tmp.json
    state: absent

- name: 'Set mode of topcat.json'
  file:
    path: /home/{{ payara_user }}/install/topcat/topcat.json
    mode: 0664
