---

- name: 'Setup authn-simple'
  import_tasks: handlers/authn-simple-handler.yml

- name: 'Set fact on host to record that authn-simple has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'authn_simple'
    value: 'true'
    no_extra_spaces: true
    create: false
