---

- name: 'Import: Check payara is running'
  import_tasks: roles/payara/tasks/status.yml

- name: 'Re-install icat-lucene'
  shell: 'su -l glassfish -c "cd /home/glassfish/install/icat.lucene; ./setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0
