---

- name: 'Restart payara'
  import_tasks: roles/payara/handlers/payara-handler.yml

- name: 'Setup icat-server'
  import_tasks: handlers/icat-server-handler.yml

- name: 'Set fact on host to record that icat-server has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'icat_server'
    value: 'true'
    no_extra_spaces: true
    create: false
