---

- name: 'Install common ICAT dependencies'
  package: name={{ item }} state=present
  with_items:
  - python-suds
  - python-requests

- name: 'Install ICAT dependencies for Red Hat systems'
  package: name={{ item }} state=present
  with_items:
  - MySQL-python
  - mysql-connector-java
  when: ansible_os_family == 'RedHat'

- name: 'Install Java packages for Debian systems'
  package: name={{ item }} state=present
  with_items:
  - python-mysqldb
  - libmysql-java
  when: ansible_os_family == 'Debian'

- name: 'Create symlink to MySQL Connector library'
  file:
    src: /usr/share/java/mysql-connector-java.jar
    path: /home/glassfish/payara41/glassfish/domains/domain1/lib/ext/mysql-connector-java.jar
    state: link
    owner: glassfish
    group: glassfish

- name: 'Check ICAT Server package'
  stat:
    path: /home/glassfish/downloads/icat.server-4.9.1-distro.zip
  register: packageResult

- name: 'Download ICAT Server'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/icat.server/4.9.1/icat.server-4.9.1-distro.zip
    dest: /home/glassfish/downloads
    owner: glassfish
    group: glassfish
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check ICAT Server installation'
  stat:
    path: /home/glassfish/install/icat.server
  register: installationResult

- name: 'Unarchive ICAT Server if not installed'
  unarchive:
    src: /home/glassfish/downloads/icat.server-4.9.1-distro.zip
    dest: /home/glassfish/install
    remote_src: true
    owner: glassfish
    group: glassfish
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Create ICAT Server config directory'
  file:
    path: /home/glassfish/config
    state: directory
    owner: glassfish
    group: glassfish
    mode: 0755

- name: 'Copy over glassfish setup.properties'
  copy:
    src: roles/payara/files/setup.properties
    dest: /home/glassfish/config/1-part
    owner: glassfish
    group: glassfish
    mode: 0644

- name: 'Copy over ICAT Server setup.properties'
  copy:
    src: files/setup.properties
    dest: /home/glassfish/config/2-part
    owner: glassfish
    group: glassfish
    mode: 0644

- name: 'Configure ICAT Server setup.properties by concatenation of files in /home/glassfish/config'
  assemble:
    src: /home/glassfish/config
    dest: /home/glassfish/install/icat.server/setup.properties
    delimiter: '\n'
    owner: glassfish
    group: glassfish
    mode: 0600
  notify:
  - icat-server-handler

- name: 'Configure ICAT Server run.properties'
  copy:
    src: files/run.properties
    dest: /home/glassfish/install/icat.server/run.properties
    owner: glassfish
    group: glassfish
    mode: 0664
  notify:
  - icat-server-handler

- name: 'Configure ICAT Server logback.xml'
  copy:
    src: files/logback.xml
    dest: /home/glassfish/install/icat.server/logback.xml
    owner: glassfish
    group: glassfish
    mode: 0664
  notify:
  - icat-server-handler
